# Dockerfile for dbt
FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libicu-dev \
    less \
    openssh-server \
    && mkdir -p /var/log \
    && touch /var/log/auth.log \
    && mkdir /var/run/sshd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# Configure SSH
RUN echo "root:3541" | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Set environment variables
ENV DBT_PROFILES_DIR=/dbt/profiles

# Create necessary directories
WORKDIR /dbt

# Install dbt-core and required adapters
RUN pip install --no-cache-dir \
    dbt-core \
    dbt-trino

# Copy your dbt project files
COPY profiles/profiles.yml /dbt/profiles/
COPY project /dbt/project/

# Copy and setup starter script
COPY scripts/dbt-starter.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/dbt-starter.sh

EXPOSE 22 

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/dbt-starter.sh"]